version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped
  
  app:
    container_name: backend-adota_pet
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - /src/node_modules
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    command: ["npm", "run", "start:dev"]

networks:
  app-network:
    driver: bridge

volumes:
  postgres:
